// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RedirectController from "./redirect_controller";
application.register("redirect", RedirectController)

import Recaptchav2Controller from "./recaptcha_v2_controller";
application.register("recaptcha-v2", Recaptchav2Controller)

import TimerController from "./timer_controller";
application.register("timer", TimerController)

import AnswersController from "./answers_controller";
application.register("answers", AnswersController)

import TeamResultsController from "./team_results_controller";
application.register("team-results", TeamResultsController)